builddrafts = false
canonifyurls = false
languageCode = "en"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

theme = "hugo-goa"

author = "Burak KADİRBEYOĞLU"
title = "Burak KADİRBEYOĞLU"

## Hugo Built-in Features
googleAnalytics = "G-P4NXQ62ZKS"
enableRobotsTXT = true

## Site Settings
[params]
author = "Burak KADİRBEYOĞLU"
intro = ""
description = """
Senior software consultant and developer.  
<br/>
Specializes in cloud backend.
"""
authorimage = "profile_picture.jpg"

## Site Meta Settings
[params.meta]
description = "Burak KADİRBEYOĞLU - Senior software developer"
keywords = "kadirbeyoğlu, kadirbeyoglu, burak kadirbeyoğlu, kadirbeyoğlu ailesi, senior software engineer, senior software developer, senior web developer, senior backend developer, cloud backend, engineer, developer, software development consultant, software architect, freelance, back-end, backend, full-stack developer, fullstack developer"

## Social Accounts
[params.social]
github = "bkadirbeyoglu"
stackoverflow = "916538/burakk"
linkedin = "bkadirbeyoglu"
twitter = "bkadirbeyoglu"
email = "bkadirbeyoglu@gmail.com"

## Extras
[params.extra]
copyright = "© 2023. Burak KADİRBEYOĞLU. [Some Rights Reserved](https://creativecommons.org/licenses/by/3.0/)."
poweredby = false
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false
